# -*- coding: utf-8 -*-
"""Final Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13HmxxgdwN8F_mBgcFqAZ5EmpkrxjT3pk
"""

import csv
import os

class Task:
    def __init__(self, name, description, priority):
        self.name = name
        self.description = description
        self.priority = priority

    def __str__(self):
        return f"Name: {self.name}, Description: {self.description}, Priority: {self.priority}"

class TodoList:
    def __init__(self, filename="tasks.csv"):
        self.filename = filename
        self.tasks = []
        self.load_tasks()

    def add_task(self, task):
        self.tasks.append(task)
        self.save_tasks()

    def delete_task(self, task_index):
        if 0 <= task_index < len(self.tasks):
            del self.tasks[task_index]
            self.save_tasks()
            return True
        return False

    def view_tasks(self):
        if not self.tasks:
            print("\nNo tasks in the list.")
            return
        print("\n--- Your Tasks ---")
        for i, task in enumerate(self.tasks):
            print(f"{i + 1}. {task}")
        print("--------------------")


    def save_tasks(self):
        with open(self.filename, mode='w', newline='', encoding='utf-8') as file:
            writer = csv.writer(file)
            writer.writerow(['Name', 'Description', 'Priority'])
            for task in self.tasks:
                writer.writerow([task.name, task.description, task.priority])

    def load_tasks(self):
        if not os.path.exists(self.filename):
            return
        try:
            with open(self.filename, mode='r', newline='', encoding='utf-8') as file:
                reader = csv.reader(file)
                header = next(reader, None)
                if not header:
                    return
                for row in reader:
                    if len(row) == 3:
                        name, description, priority = row
                        self.tasks.append(Task(name, description, priority))
        except (FileNotFoundError, StopIteration):
            self.tasks = []

def get_priority_from_user():
    while True:
        print("\nSelect priority:")
        print("1. High")
        print("2. Medium")
        print("3. Low")
        choice = input("Enter choice (1-3): ")
        if choice == '1':
            return "High"
        elif choice == '2':
            return "Medium"
        elif choice == '3':
            return "Low"
        else:
            print("Invalid choice. Please enter 1, 2, or 3.")

def main_menu():
    todo_list = TodoList()

    while True:
        print("\n--- To-Do List Menu ---")
        print("1. Add Task")
        print("2. Delete Task")
        print("3. View All Tasks")
        print("4. Exit")

        choice = input("Enter your choice: ")

        if choice == '1':
            name = input("Enter task name: ")
            description = input("Enter task description: ")
            priority = get_priority_from_user()
            new_task = Task(name, description, priority)
            todo_list.add_task(new_task)
            print("Task added successfully.")

        elif choice == '2':
            if not todo_list.tasks:
                print("No tasks to delete.")
                continue
            todo_list.view_tasks()
            try:
                task_num_str = input("Enter the number of the task to delete: ")
                task_num = int(task_num_str)
                if todo_list.delete_task(task_num - 1):
                    print("Task deleted successfully.")
                else:
                    print("Invalid task number.")
            except ValueError:
                print("Invalid input. Please enter a number.")

        elif choice == '3':
            todo_list.view_tasks()

        elif choice == '4':
            print("Exiting program.")
            break

        else:
            print("Invalid choice. Please select a valid option.")

if __name__ == "__main__":
    main_menu()